#!/usr/bin/env bash
# This script displays the IP address of subdomains for a given domain

# Function to check a subdomain
check_subdomain() {
    local domain=$1
    local sub=$2
    ip=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print $5}')
    echo "The subdomain $sub is a A record and points to $ip"
}

# Main
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02; do
        check_subdomain "$domain" "$sub"
    done
else
    check_subdomain "$domain" "$subdomain"
fi
