#!/usr/bin/env bash
# This script audits subdomains of a given domain and displays their A records

# Function to get info about a subdomain
get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    # Use dig to get the DNS record and parse it with awk
    record=$(dig ${subdomain}.${domain} | awk '/ANSWER SECTION:/ {getline; print}')
    type=$(echo $record | awk '{print $4}')
    dest=$(echo $record | awk '{print $5}')
    echo "The subdomain ${subdomain} is a ${type} record and points to ${dest}"
}

domain=$1
subdomain=$2

# If no specific subdomain is passed, check all 4 in order
if [ -z "$subdomain" ]; then
    for sd in www lb-01 web-01 web-02; do
        get_subdomain_info $domain $sd
    done
else
    # Only check the specified subdomain
    get_subdomain_info $domain $subdomain
fi
